"""Updating Migration

Revision ID: 576768a4c6a8
Revises: cdef7f7b8fa5
Create Date: 2019-09-30 09:21:22.628113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576768a4c6a8'
down_revision = 'cdef7f7b8fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
